"""
Agent & Search Router
app/routers/agent_router.py

Exposes the Multi-Agent RFQ pipeline, dynamic reasoning chat, and raw vector search.
"""

import logging
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

# Import pipeline functions
from app.pipeline.agent_pipeline import execute_agentic_chat, run_full_rfq_analysis

# Import retrieval service for the raw search endpoint
from app.pipeline.optimization_service import retrieve_and_rerank

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/agents", tags=["AI Agents & Search"])

# ==========================================
# 📦 PYDANTIC MODELS (API Contracts)
# ==========================================
class AgentRequest(BaseModel):
    query: str = Field(..., description="The user's instruction or question for the AI assistant.")

class AgentResponse(BaseModel):
    answer: str = Field(..., description="The final text response generated by the multi-agent loop.")

class SearchRequest(BaseModel):
    query: str = Field(..., description="The search query.")
    initial_k: int = Field(40, description="Initial number of chunks to retrieve before reranking.")
    final_k: int = Field(10, description="Final number of chunks to return after reranking.")

class SearchResponse(BaseModel):
    status: str
    query: str
    results: List[Dict[str, Any]]
    confidence_score: float

class RFQPipelineRequest(BaseModel):
    file_path: str = Field(..., description="The local path to the uploaded RFQ document.")


# ==========================================
# 🚀 1. FULL RFQ PIPELINE ENDPOINT
# ==========================================
@router.post("/analyze-rfq", summary="Run Sequential RFQ Multi-Agent Pipeline")
async def analyze_rfq_endpoint(request: RFQPipelineRequest):
    """
    Triggers the end-to-end ingestion and multi-agent extraction pipeline.
    (Doc -> BOQ -> Risk -> Summary)
    """
    logger.info(f"📄 Received RFQ Analysis Request for: {request.file_path}")
    try:
        pipeline_response = await run_full_rfq_analysis(request.file_path)
        
        if pipeline_response.get("status") == "error":
            raise HTTPException(status_code=500, detail=pipeline_response.get("message"))
            
        return pipeline_response
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ RFQ Router Error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Critical failure in the RFQ pipeline.")


# ==========================================
# 🧠 2. AGENTIC REASONING ENDPOINT (/agent)
# ==========================================
@router.post("/agent", response_model=AgentResponse, summary="Trigger AI Agent Reasoning")
async def ask_agent(request: AgentRequest):
    """
    Triggers the dynamic ReAct agent loop capable of using tools 
    like calculate_totals, extract_table, and search_documents.
    """
    logger.info(f"📩 Received Agent Query: '{request.query}'")
    try:
        # Route through the pipeline layer rather than calling the service directly
        pipeline_response = await execute_agentic_chat(request.query)
        
        if pipeline_response.get("status") == "error":
            raise HTTPException(status_code=500, detail=pipeline_response.get("response"))
            
        return AgentResponse(answer=str(pipeline_response.get("response", "")))
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Agent Router Error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="The Agent encountered a processing error.")


# ==========================================
# 🔍 3. RAW SEARCH ENDPOINT (/search)
# ==========================================
@router.post("/search", response_model=SearchResponse, summary="Raw Vector Search & Rerank")
async def search_documents_endpoint(request: SearchRequest):
    """
    Consolidated search endpoint. Executes hybrid search + reranking 
    bypassing the reasoning agents (useful for frontend UI document viewers).
    """
    logger.info(f"🔍 Executing search for query: '{request.query}'")
    try:
        results, score = await retrieve_and_rerank(
            query=request.query,
            initial_k=request.initial_k,
            final_k=request.final_k
        )
        return SearchResponse(
            status="success",
            query=request.query,
            results=results,
            confidence_score=float(score)
        )
    except Exception as e:
        logger.error(f"❌ Search routing failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Search execution failed.")